services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  app:
    image: d3vle0/yas-web
    env_file:
      - ./backend/.env
    environment:
      MONGODB_URI: mongodb://mongo:27017/yas-web
      CORS_ORIGIN: http://localhost:7001
      FRONTEND_DIST: /app/public
      PORT: 7001
    depends_on:
      - mongo
    ports:
      - "7001:7001"
    restart: unless-stopped

volumes:
  mongo-data:
